### ISSUE TITLE
No plugin and no Widget after installed this plugin.

### ISSUE THREAD

**Issue by alesaint** [NicolasSiver/nodebb-widget-ns-birthdays#1]
Hello,

Thx for your job.

Just one question, after installed and enabled this plugin in my nodebb forum 0.7.X, I didn't see this one in the installed plugin list and no widget added from the ACP (extend/widgets)

Any idea?

Best regards

**Comment by NicolasSiver** [comment]
Maybe some conflict.
It works well on `0.9.x`

**Comment by Terra-F** [comment]
I also can't get the plugin working. When starting NodeBB, I find this in the logs:

```
20/11 15:22:41 [27497] - error: Error: Cannot find module 'templates.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at /home/username/nodebb/node_modules/nodebb-widget-ns-birthdays/widget/nodebb.js:43:27
    at Object.<anonymous> (/home/username/nodebb/node_modules/nodebb-widget-ns-birthdays/widget/nodebb.js:45:3)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at /home/username/nodebb/node_modules/nodebb-widget-ns-birthdays/widget/job.js:6:18
    at Object.<anonymous> (/home/username/nodebb/node_modules/nodebb-widget-ns-birthdays/widget/job.js:91:3)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
20/11 15:22:41 [27497] - warn: [plugins] Unable to parse library for: nodebb-widget-ns-birthdays
20/11 15:22:41 [27497] - verbose: [plugins] Loaded plugin: nodebb-widget-ns-birthdays
```

What should I do?

**Comment by NicolasSiver** [comment]
What NodeBB version do you use?

**Comment by Terra-F** [comment]
We are using v1.7.0.

**Comment by Terra-F** [comment]
Might it have something to do with `npm WARN eonasdan-bootstrap-datetimepicker@4.17.47 requires a peer of moment-timezone@^0.4.0 but none was installed.` or is it unrelated?

**Comment by NicolasSiver** [comment]
It's unrelated. But there is a high probability that plugin just does not support 1.7.

Every minor version 1.2, 1.3, ..., 1.7, NodeBB team does breaking changes.

**Comment by Terra-F** [comment]
Right. Well, I had the same with 1.6. But ummm... my programming skills aren't good enough to get to bottom of the issue and provide a fix myself, so I will keep an eye out for this repository. Thank you anyways for this and other plugins! Awesome work.
